export default {
    ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
    CLEAR_PRODUCT_DETAILS: 'CLEAR_PRODUCT_DETAILS',
    CREATE_GUEST_ORDER: 'CREATE_GUEST_ORDER',
    CREATE_USER_ORDER: 'CREATE_USER_ORDER',
    DELETE_ITEM_FROM_CART: 'DELETE_ITEM_FROM_CART',
    GET_ACTIVE_CART: 'GET_ACTIVE_CART',
    GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
    GET_CART_TOTALS: 'GET_CART_TOTALS',
    GET_GUEST_ORDER_DETAILS: 'GET_GUEST_ORDER_DETAILS',
    GET_PRODUCT_DETAILS: 'GET_PRODUCT_DETAILS',
    GET_SCHEDULE: 'GET_SCHEDULE',
    GET_USER_ORDER_DETAILS: 'GET_USER_ORDER_DETAILS',
    SIGN_IN: 'SIGN_IN',
    SIGN_OUT: 'SIGN_OUT',
    SIGN_UP: 'SIGN_UP'
}